### PR TITLE
Supports insert operations

### PR DESCRIPTION
**Pull request by rfyu**
Support using Trino to perform insert and update operations on primary key tables

### CODE REVIEW

**Comment by JingsongLi** [comment]
Can you add some tests?

**Comment by JingsongLi** [comment]
What trino version do you use? Maybe we can get rid of old version now.

**Comment by rfyu** [comment]
> Can you add some tests?

Sure, I will do it.

**Comment by rfyu** [comment]
> What trino version do you use? Maybe we can get rid of old version now.

We are currently using trino-418, but we will upgrade once the upsert functionality is ready.

**Comment by rfyu** [comment]
> What trino version do you use? Maybe we can get rid of old version now.

Currently, only Trino-440 supports the merge operation, and there are some unresolved bugs in the older trino versions.So are we directly removing support for older versions of Trino?

**Comment by JingsongLi** [comment]
Looks good to me! Thanks @rfyu

**Pull request merged**
